In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [7]:
### Instructions pour l'installation dans JupyterLab : 
# https://ipywidgets.readthedocs.io/en/latest/user_install.html#installing-in-jupyterlab-3-0
# Utiliser id√©alement JupyterLab 3.0

from ipywidgets import (
    interact, IntSlider, Checkbox,
    interactive, SelectMultiple,
    SelectionRangeSlider, Layout,
    jslink, fixed,
    HTML, HBox)

In [2]:
from ipyleaflet import (Map,
                        Marker,
                        basemap_to_tiles,
                        basemaps,
                        CircleMarker,
                        MarkerCluster,
                        LayerGroup, 
                        LayersControl,
                        WidgetControl,
                        Popup,
                        ScaleControl
                       )

In [3]:
import pprint
import csv
import ast
import re

from collections import Counter
from operator import itemgetter

import sqlite3 as sql
import time

from importlib import reload
from shutil import copyfile

import math

In [4]:
tombes_coord = pd.read_csv('additional_data/Tombes_coord.txt', sep=';')
tombes_coord.head()

,FID,FID_,Entity,Layer,Color,Linetype,Elevation,LineWt,RefName,Angle,IDTombe,Inventaire,Secteur,Coordonnee,Coordonn_1,Campagne,Datation,Anciennes_,POINT_X,POINT_Y
0,0,0,Point,Tombb,198,Continuous,"0,000000000000000",25,,"0,000000000000000","3,000000000000000","308,000000000000000","1,000000000000000","1093,000000000000000","-261,000000000000000",2008-2009,"3,000000000000000","261,000000000000000","30,444143165200000","19,615288575299999"
1,1,0,Point,Tombb,198,Continuous,"0,000000000000000",25,,"0,000000000000000","4,000000000000000","309,000000000000000","1,000000000000000","1075,000000000000000","-264,000000000000000",2008-2009,"3,000000000000000","264,000000000000000","30,444118477100002","19,615130452700001"
2,2,0,Point,Tombb,198,Continuous,"0,000000000000000",25,,"0,000000000000000","5,000000000000000","310,000000000000000","1,000000000000000","1058,000000000000000","-261,000000000000000",2008-2009,"3,000000000000000","261,000000000000000","30,444146316600001","19,614981639900002"
3,3,0,Point,Tombb,198,Continuous,"0,000000000000000",25,,"0,000000000000000","6,000000000000000","311,000000000000000","1,000000000000000","1072,000000000000000","-262,000000000000000",2008-2009,"3,000000000000000","262,000000000000000","30,444136286399999","19,615104324000001"
4,4,0,Point,Tombb,198,Continuous,"0,000000000000000",25,,"0,000000000000000","7,000000000000000","312,000000000000000","1,000000000000000","1071,000000000000000","-266,000000000000000",2008-2009,"1,000000000000000","266,000000000000000","30,444101298100001","19,615095194300000"

In [5]:
data = [(i,'t'+ str(v['IDTombe']).replace(',000000000000000', ''), float(v['POINT_X'].replace(',','.')), float(v['POINT_Y'].replace(',','.'))) for i,v in tombes_coord.iterrows()]
data[:3]

[(0, 't3', 30.4441431652, 19.6152885753),
 (1, 't4', 30.4441184771, 19.6151304527),
 (2, 't5', 30.4441463166, 19.6149816399)]

In [24]:
## 

esri_word_topo = basemap_to_tiles(basemaps.Esri.WorldTopoMap)
#¬†open_street_map = basemap_to_tiles(basemaps.OpenStreetMap.Mapnik)
esri_sat = basemap_to_tiles(basemaps.Esri.WorldImagery)
#¬†gaode_sat = basemap_to_tiles(basemaps.Gaode.Satellite)

## https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Styling.html
m1 = Map(layers=(esri_word_topo, esri_sat), center=(19.614, 30.443670), layout=Layout(width='100%', height='600px'),\
        zoom_control=True  , zoom=17 #, scroll_wheel_zoom=True
       )

control = LayersControl(name='layCont', position='topright')
m1.add_control(control)

m1.add_control(ScaleControl(position='topleft'))

In [25]:
idx = 0
markers = []


for d in data:
    circle = CircleMarker(location=(d[3], d[2]), color='DarkSlateBlue', name=d[1], radius=0)
    
                          #, \ radius = int(math.log((v['effectif'] + 1) * 3, 2)), weight=1)
    #¬†message.value = f"<h4>{j['place_name']} ({j['count_persons']})</h4>" + p_elements
    # a = HBox([message], layout=Layout(width='200px', height='200px', overflow_y='auto',overflow="auto"))

    #message = HTML()
    #message.value = f"{v['university_name']} ({v['effectif']})"

    #a = HBox([message], layout=Layout(width='100px', height='200px', overflow="auto")) # overflow_y='auto',

    #circle.popup = a

    markers.append(circle)


print("Markers' number " + str(len(markers)))

mc = MarkerCluster(markers=markers)
lg = LayerGroup(name = 'Tombes', layers = markers)
m1.add_layer(lg) # my_dict[idx])
m1
#    idx += 1

Markers' number 732

Map(center=[19.614, 30.44367], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title', 'zo‚Ä¶